spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        provider:

          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

        registration:
          naver:
            client-id: LF4M4FV2nBXHhCkb1kCu
            client-secret: krL0zRsqhl
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, nickname
            client-name: Naver

          kakao:
            authorization-grant-type: authorization_code
            client-id: 111e6bb27d40bdb8fee9064791def867
            client-secret: uOAB4iSe12MWInWgdxAabg1Ry4ajdIoo
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
            client-authentication-method: POST
            client-name: Kakao

          google:
            client-id: 85287933912-v90j2t6si0jo3qefhs3hhmau661rf3nb.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email